export interface ProductDetail {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  thumbnails: string[]
  category: string
  description: string
  fabric: string
  fit: string
  colors: string[]
  sizes: string[]
  tags?: string[]
  designer?: string
  customizable: boolean
  details: Record<string, string>
  designerQuote?: string
}

const PRODUCTS: ProductDetail[] = [
  {
    id: 'p1',
    name: '定制创意印花 T恤',
    price: 199,
    originalPrice: 299,
    image: 'https://picsum.photos/seed/3c604c9a1e87/400/500',
    thumbnails: [
      'https://picsum.photos/seed/374f813ba69b/400/500',
      'https://picsum.photos/seed/8d59cc3834da/400/500',
      'https://picsum.photos/seed/16843390e3cf/400/500',
    ],
    category: '基础款',
    description: '采用 100% 高品质精梳棉，手感柔软亲肤。支持多区域个性化定制，让你的创意灵感跃然衣上。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['白色', '黑色', '灰色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Canvas Ready'],
    designer: 'Jordan.Design',
    customizable: true,
    details: { '材质': '100% 精梳棉', '克重': '220g 重磅', '版型': '宽松落肩' },
    designerQuote: '这不仅是一件 T恤，更是你表达自我的画布。我们致力于提供最高品质的基础款，让你的每一个设计都能完美呈现。',
  },
  {
    id: 'p2',
    name: '重磅廓形圆领衫',
    price: 199,
    image: 'https://picsum.photos/seed/3c604c9a1e87/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a1b2c3d4e5f6/400/500',
      'https://picsum.photos/seed/b2c3d4e5f6a1/400/500',
      'https://picsum.photos/seed/c3d4e5f6a1b2/400/500',
    ],
    category: '基础款',
    description: '重磅棉质廓形剪裁，宽身不挑身材，极简主义的首选基础款。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['黑色', '深灰', '燕麦色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    customizable: false,
    details: { '材质': '100% 棉', '克重': '260g', '版型': '廓形宽身' },
  },
  {
    id: 'p3',
    name: '极简连帽卫衣',
    price: 399,
    image: 'https://picsum.photos/seed/8a17ad401514/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d4e5f6a1b2c3/400/500',
      'https://picsum.photos/seed/e5f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/f6a1b2c3d4e5/400/500',
    ],
    category: '基础款',
    description: '极简风格的连帽卫衣，采用优质棉质面料，舒适透气，是日常穿搭的百搭之选。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['灰色', '黑色', '藏青色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    customizable: false,
    details: { '材质': '80% 棉 20% 聚酯纤维', '克重': '380g', '版型': '宽松落肩' },
  },
  {
    id: 'p4',
    name: '阔腿束口短裤',
    price: 159,
    image: 'https://picsum.photos/seed/ef2c5fff6450/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a1f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/b2f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/c3f6a1b2c3d4/400/500',
    ],
    category: '基础款',
    description: '宽松阔腿剪裁搭配束口设计，轻松打造休闲运动风。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['黑色', '军绿色', '卡其色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    customizable: false,
    details: { '材质': '100% 棉', '克重': '200g', '版型': '阔腿束口' },
  },
  {
    id: 'p5',
    name: '精梳棉长袖',
    price: 249,
    image: 'https://picsum.photos/seed/c8d4d08aa439/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d1f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/e2f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/f3f6a1b2c3d4/400/500',
    ],
    category: '基础款',
    description: '精梳棉材质长袖T恤，亲肤柔软，四季皆宜的基础单品。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['白色', '灰色', '深蓝色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    customizable: false,
    details: { '材质': '100% 精梳棉', '克重': '180g', '版型': '常规直身' },
  },
  {
    id: 'p6',
    name: '重磅基础圆领T恤',
    price: 299,
    image: 'https://picsum.photos/seed/5c97e3382aae/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a4f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/b5f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/c6f6a1b2c3d4/400/500',
    ],
    category: '核心款',
    description: '重磅混纺面料圆领T恤，挺括有型，耐洗不易变形。',
    fabric: '混纺',
    fit: '常规',
    colors: ['白色', '黑色', '深灰色'],
    sizes: ['S', 'M', 'L', 'XL'],
    customizable: false,
    details: { '材质': '60% 棉 40% 聚酯纤维', '克重': '240g', '版型': '常规合身' },
  },
  {
    id: 'p7',
    name: '全棉连帽卫衣',
    price: 589,
    originalPrice: 699,
    image: 'https://picsum.photos/seed/cc1602a6ae6c/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d7f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/e8f6a1b2c3d4/400/500',
      'https://picsum.photos/seed/f9f6a1b2c3d4/400/500',
    ],
    category: '核心款',
    description: '全棉混纺连帽卫衣，内里加绒处理，秋冬必备保暖单品。',
    fabric: '混纺',
    fit: '常规',
    colors: ['霜灰色', '墨黑色', '焦糖色'],
    sizes: ['S', 'M', 'L', 'XL'],
    customizable: false,
    details: { '材质': '85% 棉 15% 聚酯纤维', '克重': '420g', '版型': '常规合身' },
  },
  {
    id: 'p8',
    name: '艺术家合作款短袖',
    price: 899,
    image: 'https://picsum.photos/seed/18b9254c6303/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a0b1c2d3e4f5/400/500',
      'https://picsum.photos/seed/b1c2d3e4f5a0/400/500',
      'https://picsum.photos/seed/c2d3e4f5a0b1/400/500',
    ],
    category: '设计师款',
    description: '与艺术家 Alex Chen 联名合作，独家艺术印花设计，限量发售。',
    fabric: '涤纶',
    fit: '修身',
    colors: ['白色', '黑色'],
    sizes: ['M', 'L', 'XL'],
    designer: 'Alex Chen',
    customizable: false,
    details: { '材质': '100% 涤纶', '克重': '160g', '版型': '修身剪裁' },
    designerQuote: '每一件都是一个小型画展，穿上它，你就是在展示一种态度。',
  },
  {
    id: 'p9',
    name: '手工水洗丹宁夹克',
    price: 1299,
    image: 'https://picsum.photos/seed/ebbd34802107/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d3e4f5a0b1c2/400/500',
      'https://picsum.photos/seed/e4f5a0b1c2d3/400/500',
      'https://picsum.photos/seed/f5a0b1c2d3e4/400/500',
    ],
    category: '定制款',
    tags: ['New'],
    description: '手工水洗做旧工艺，每件都独一无二。限量定制，尊享个性体验。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['复古蓝', '深蓝', '黑色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    customizable: true,
    details: { '材质': '100% 丹宁棉', '克重': '480g', '版型': '宽松廓形' },
  },
  {
    id: 'p10',
    name: '莫代尔混纺T恤',
    price: 349,
    image: 'https://picsum.photos/seed/91c83495b360/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a5b6c7d8e9f0/400/500',
      'https://picsum.photos/seed/b6c7d8e9f0a5/400/500',
      'https://picsum.photos/seed/c7d8e9f0a5b6/400/500',
    ],
    category: '核心款',
    description: '莫代尔混纺面料，丝滑触感，垂坠感极佳，通勤休闲两相宜。',
    fabric: '混纺',
    fit: '常规',
    colors: ['米白色', '灰色', '墨绿色'],
    sizes: ['S', 'M', 'L', 'XL'],
    customizable: false,
    details: { '材质': '50% 莫代尔 50% 棉', '克重': '160g', '版型': '常规合身' },
  },
  {
    id: 'p11',
    name: '廓形立领衬衫',
    price: 749,
    image: 'https://picsum.photos/seed/d6148e3dc9b7/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d8e9f0a1b2c3/400/500',
      'https://picsum.photos/seed/e9f0a1b2c3d8/400/500',
      'https://picsum.photos/seed/f0a1b2c3d8e9/400/500',
    ],
    category: '设计师款',
    description: '与设计师 Li Wei 合作款，廓形立领剪裁，打破传统衬衫的刻板印象。',
    fabric: '涤纶',
    fit: '修身',
    colors: ['白色', '淡蓝色'],
    sizes: ['M', 'L', 'XL'],
    designer: 'Li Wei',
    customizable: false,
    details: { '材质': '100% 涤纶', '克重': '140g', '版型': '修身廓形立领' },
    designerQuote: '衬衫不需要被束缚，廓形立领是一种自由的表达。',
  },
  {
    id: 's1',
    name: '简约基础款 T恤',
    price: 299,
    image: 'https://picsum.photos/seed/098e0d9fcdd3/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a1b2c3d4e566/400/500',
      'https://picsum.photos/seed/b2c3d4e566a1/400/500',
      'https://picsum.photos/seed/c3d4e566a1b2/400/500',
    ],
    category: '基础款',
    description: '大地色系 / 有机棉。天然有机棉面料，温柔呵护肌肤。',
    fabric: '棉质',
    fit: '常规',
    colors: ['沙色', '橄榄绿', '灰棕色'],
    sizes: ['S', 'M', 'L', 'XL'],
    customizable: false,
    details: { '材质': '100% 有机棉', '克重': '180g', '版型': '常规合身' },
  },
  {
    id: 's2',
    name: '重磅廓形连帽衫',
    price: 599,
    image: 'https://picsum.photos/seed/ea141792a20f/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d4e566a1b2c3/400/500',
      'https://picsum.photos/seed/e566a1b2c3d4/400/500',
      'https://picsum.photos/seed/f66a1b2c3d4e/400/500',
    ],
    category: '核心款',
    description: '落肩设计 / 舒适透气。重磅混纺面料，打造舒适有型的街头轮廓。',
    fabric: '混纺',
    fit: '宽松',
    colors: ['炭灰色', '藏蓝色', '黑色'],
    sizes: ['S', 'M', 'L', 'XL'],
    customizable: false,
    details: { '材质': '70% 棉 30% 聚酯纤维', '克重': '400g', '版型': '廓形落肩' },
  },
  {
    id: 's3',
    name: '极简立领卫衣',
    price: 459,
    image: 'https://picsum.photos/seed/a0e3d63f8424/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a7b8c9d0e1f2/400/500',
      'https://picsum.photos/seed/b8c9d0e1f2a7/400/500',
      'https://picsum.photos/seed/c9d0e1f2a7b8/400/500',
    ],
    category: '设计师款',
    description: '沙色系列 / 限量版。极简立领设计，低调中见格调。',
    fabric: '涤纶',
    fit: '修身',
    colors: ['沙色', '米色'],
    sizes: ['M', 'L', 'XL'],
    designer: 'Studio_99',
    customizable: false,
    details: { '材质': '100% 涤纶', '克重': '200g', '版型': '修身立领' },
  },
  {
    id: 's4',
    name: '修身针织短袖',
    price: 389,
    image: 'https://picsum.photos/seed/d56819f894d3/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d0e1f2a3b4c5/400/500',
      'https://picsum.photos/seed/e1f2a3b4c5d0/400/500',
      'https://picsum.photos/seed/f2a3b4c5d0e1/400/500',
    ],
    category: '核心款',
    description: '深灰色 / 经典剪裁。精细针织工艺，修身显瘦。',
    fabric: '棉质',
    fit: '修身',
    colors: ['深灰色', '黑色', '藏青色'],
    sizes: ['S', 'M', 'L'],
    customizable: false,
    details: { '材质': '95% 棉 5% 氨纶', '克重': '170g', '版型': '修身合身' },
  },
  {
    id: 's5',
    name: '全棉连帽卫衣',
    price: 589,
    image: 'https://picsum.photos/seed/cc1602a6ae6c/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a3b4c5d6e7f8/400/500',
      'https://picsum.photos/seed/b4c5d6e7f8a3/400/500',
      'https://picsum.photos/seed/c5d6e7f8a3b4/400/500',
    ],
    category: '核心款',
    description: '重磅棉质 / 加绒内里。秋冬保暖必备，加绒内里温暖过冬。',
    fabric: '混纺',
    fit: '常规',
    colors: ['霜灰色', '墨黑色', '焦糖色'],
    sizes: ['S', 'M', 'L', 'XL'],
    customizable: false,
    details: { '材质': '85% 棉 15% 聚酯纤维', '克重': '420g', '版型': '常规合身' },
  },
  {
    id: 's6',
    name: '艺术家合作款短袖',
    price: 899,
    image: 'https://picsum.photos/seed/18b9254c6303/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d6e7f8a3b4c5/400/500',
      'https://picsum.photos/seed/e7f8a3b4c5d6/400/500',
      'https://picsum.photos/seed/f8a3b4c5d6e7/400/500',
    ],
    category: '设计师款',
    description: '联名限量 / 艺术印花。独家联名艺术印花，每件皆为收藏品。',
    fabric: '涤纶',
    fit: '修身',
    colors: ['白色', '黑色'],
    sizes: ['M', 'L', 'XL'],
    designer: 'Alex Chen',
    customizable: false,
    details: { '材质': '100% 涤纶', '克重': '160g', '版型': '修身剪裁' },
    designerQuote: '艺术不是挂在墙上的，穿在身上才是最好的展示。',
  },
  {
    id: 's7',
    name: '手工水洗丹宁夹克',
    price: 1299,
    image: 'https://picsum.photos/seed/ebbd34802107/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a9b0c1d2e3f4/400/500',
      'https://picsum.photos/seed/b0c1d2e3f4a9/400/500',
      'https://picsum.photos/seed/c1d2e3f4a9b0/400/500',
    ],
    category: '定制款',
    description: '手工做旧 / 限量定制。每件都经过独立水洗工艺，独一无二。',
    fabric: '棉质',
    fit: '宽松',
    colors: ['复古蓝', '深蓝', '黑色'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    customizable: true,
    details: { '材质': '100% 丹宁棉', '克重': '480g', '版型': '宽松廓形' },
  },
  {
    id: 's8',
    name: '织锦缎棒球帽',
    price: 199,
    image: 'https://picsum.photos/seed/9e32a18bc5f1/400/500',
    thumbnails: [
      'https://picsum.photos/seed/d2e3f4a5b6c7/400/500',
      'https://picsum.photos/seed/e3f4a5b6c7d2/400/500',
      'https://picsum.photos/seed/f4a5b6c7d2e3/400/500',
    ],
    category: '配饰',
    description: '限定配色 / 可调节。织锦缎面料搭配精致刺绣，质感出众。',
    fabric: '混纺',
    fit: '常规',
    colors: ['黑色', '酒红色', '墨绿色'],
    sizes: ['均码'],
    customizable: false,
    details: { '材质': '60% 棉 40% 聚酯纤维', '工艺': '织锦缎 + 刺绣', '帽型': '经典棒球帽' },
  },
  {
    id: 's9',
    name: '机能斜挎包',
    price: 259,
    image: 'https://picsum.photos/seed/2d6a4f8c3e71/400/500',
    thumbnails: [
      'https://picsum.photos/seed/a5b6c7d8e9f0/400/500',
      'https://picsum.photos/seed/b6c7d8e9f0a1/400/500',
      'https://picsum.photos/seed/c7d8e9f0a1b2/400/500',
    ],
    category: '配饰',
    description: '防水面料 / 多隔层。轻量机能设计，日常通勤轻松收纳。',
    fabric: '涤纶',
    fit: '常规',
    colors: ['黑色', '军绿色', '深灰色'],
    sizes: ['均码'],
    customizable: false,
    details: { '材质': '100% 防水涤纶', '容量': '3L', '结构': '主仓 + 前袋 + 内隔层' },
  },
]

export function getProductDetail(id: string): ProductDetail | undefined {
  return PRODUCTS.find(p => p.id === id)
}

export function getAllProductIds(): string[] {
  return PRODUCTS.map(p => p.id)
}
